name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  Build-Publish:
    name: Build-Publish
    needs: pre-ci
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/subql-ethereum'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

    #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed-types-ethereum
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common-ethereum
        with:
          paths: packages/common-ethereum

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      - run: yarn

      - name: build
        run: yarn build

      #Publish to npm and github releases
      - name: Publish Types ethereum
        if: steps.changed-types-ethereum.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/types
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Common ethereum
        if: steps.changed-common-ethereum.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/common-ethereum
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Node
        if: steps.changed-node.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/node
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

  Build-Flare-Publish:
    name: Build-Flare-Publish
    needs: Build-Publish
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/subql-ethereum'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

    #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed-types-flare
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common-flare
        with:
          paths: packages/common-ethereum

      - uses: marceloprado/has-changed-path@v1
        id: changed-node
        with:
          paths: packages/node

      #Changes packages names
      - name: Change common ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/common-ethereum/package.json
          rename: '@subql/common-flare'

      - name: Change types ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/types/package.json
          rename: '@subql/types-flare'

      - name: Change node ethereum to flare
        uses: jaywcjlove/github-action-package@main
        with:
          path: packages/node/package.json
          rename: '@subql/node-flare'

      #update imports

      - name: Update imports to flare
        run: ./.github/workflows/scripts/update_flare_imports.sh

      - run: yarn

      - name: build
        run: yarn workspaces foreach run build

      #Publish to npm and github releases
      - name: Publish Types flare
        if: steps.changed-types-flare.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/types
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Common flare
        if: steps.changed-common-flare.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/common-ethereum
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Node
        if: steps.changed-node.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/node
          repo-token: ${{ secrets.REPO_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
